-- Week 4 Commit 26: Add token and cost tracking to audit_log
--
-- This migration adds columns to track LLM token usage and costs in the audit log.
-- Enables cost monitoring, budgeting, and optimization.

-- Add token and cost tracking columns
ALTER TABLE audit_log
ADD COLUMN IF NOT EXISTS tokens_input INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tokens_output INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cost_usd DECIMAL(10, 6) DEFAULT 0.0;

-- Create index for cost analysis queries
CREATE INDEX IF NOT EXISTS idx_audit_log_cost ON audit_log(cost_usd) WHERE cost_usd > 0;
CREATE INDEX IF NOT EXISTS idx_audit_log_tokens ON audit_log(tokens_input, tokens_output);

-- Comments for documentation
COMMENT ON COLUMN audit_log.tokens_input IS 'Number of input tokens sent to LLM (Week 4 Commit 26)';
COMMENT ON COLUMN audit_log.tokens_output IS 'Number of output tokens generated by LLM (Week 4 Commit 26)';
COMMENT ON COLUMN audit_log.cost_usd IS 'Estimated cost in USD for this request (Week 4 Commit 26)';
